### ISSUE TITLE
Add toleration settings per image cache object

### ISSUE THREAD

**Issue by jharris-** [senthilrch/kube-fledged#116]
Hello,
It is currently not possible to set a toleration in the cache spec for the job to use, only nodeSelector.

This is a problem for clusters that rely on taints to segregate workloads.

**Comment by jharris-** [comment]
Looks like this was supposed to automatically set a toleration based on a matched node's taints per resolution of issue#8 
https://github.com/senthilrch/kube-fledged/issues/8

This is not happening with my current deployment via helm of v0.8.2 on eks 1.18

**Comment by senthilrch** [comment]
@jharris- : kube-fledged adds a "generic" toleration to all Jobs that matches "any" taint. This code already exists:-
![image](https://user-images.githubusercontent.com/24295410/134812835-b5ebfdcd-fd7e-4f33-9c93-cc661e713975.png)

**Comment by jharris-** [comment]
@senthilrch I noticed that handler at the job spec but I am not seeing that on the running resources

So I have Windows EKS nodes with the following taint
```
Taints:             os=windows:NoSchedule
```

I have the nodeSelector target those nodes to cache the images via the ImageCache resource
```yaml
---
apiVersion: kubefledged.io/v1alpha2
kind: ImageCache
metadata:
  # Name of the image cache. A cluster can have multiple image cache objects
  name: imagecache-1
  # The kubernetes namespace to be used for this image cache. You can choose a different namepace as per your preference
  labels:
    app: kubefledged
    component: imagecache
spec:
  # The "cacheSpec" field allows a user to define a list of images and onto which worker nodes those images should be cached (i.e. pre-pulled).
  cacheSpec:
  # Specifies a list of images (redis:6.2.5 and mariadb:10.5.11) with a node selector, hence these images will be cached only on the nodes selected by the node selector
  - images:
    - <privaterepo>/image:v1.2.3
    nodeSelector:
      kubernetes.io/os: windows
    tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/os
        operator: Equal
        value: windows
```

The Jobs and Pods just have a toleration for the operator
```
kubectl -n kube-fledged get job job-image-4vxlq -o yaml | grep -C3 tolerations
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - emptyDir: {}
```

```
kubectl -n kube-fledged get pod pod-image-z4rzp -o yaml | grep -C3 tolerations
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - operator: Exists
  volumes:
  - emptyDir: {}
```
