### ISSUE TITLE
Where to set `--image-pull-deadline-duration`?

### ISSUE THREAD

**Issue by keypointt** [senthilrch/kube-fledged#131]
Hi Senthil,

I'm beginner of kube-fledged and I followed https://itnext.io/how-to-deploy-and-use-kube-fledged-to-cache-images-in-kubernetes-8b6b9d6c2733 to create a yaml file

`kubefledged-imagecache.yaml`
```
apiVersion: kubefledged.io/v1alpha2
kind: ImageCache
metadata:
  # Name of the image cache.
  name: imagecache1
  # The namespace to be used for this image cache.
  namespace: ppp
  labels:
    app: ppp
spec:
  # The "cacheSpec" field allows a user to define a list of images and onto which worker nodes those images should be cached (i.e. pre-pulled).
  cacheSpec:
  # Specifies a list of images (nginx:1.21.1 and tomcat:10.0.8) with no node selector, hence these images will be cached in all the nodes in the cluster
  - images:
    - repo/name:tag
    - repo/name:tag2
```

But my images is 10G and will take up to 1 hour to finish pulling, as the default is 5m so my cache apparently failed.

kubectl is giving me error
```
kubectl apply -f kubefledged-imagecache.yaml --image-pull-deadline-duration 60m
error: unknown flag: --image-pull-deadline-duration
```

and not sure where to set inside `kubefledged-imagecache.yaml`

Just curious where to set `--image-pull-deadline-duration 60m`?

Thank you.
