### ISSUE TITLE
Permission issue when purging images from cache on OpenShift

### ISSUE THREAD

**Issue by hfwen0502** [senthilrch/kube-fledged#134]
The errors shown in the ImageCache's object:
```
status:
  completionTime: "2022-02-17T21:03:39Z"
  failures:
    uk.icr.io/hf-roks-uk/in-cluster:latest:
    - message: |
        time="2022-02-17T21:03:37Z" level=fatal msg="connect: connect endpoint 'unix:///var/run/crio/crio.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded"
      node: 10.242.0.18
      reason: Error
  message: Image deletion failed for some images. Please see "failures" section
  reason: ImageCachePurge
  startTime: "2022-02-17T21:03:33Z"
  status: Failed
```

I can reproduce this by just running this job, rsh to the pod and run the crictl command.
```
apiVersion: batch/v1
kind: Job
metadata:
  name: hf-job
spec:
  template:
    spec:
      name: hf-pod
      containers:
      - name: c
        image: senthilrch/kubefledged-cri-client:v0.9.0
        command: ["tail", "-f", "/dev/null"]
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: host
      hostNetwork: true
      volumes:
      - hostPath:
          path: /
          type: Directory
        name: host

      restartPolicy: Never
      imagePullSecrets:
        - name: all-icr-io
```
As you can see, even though adding the additional privilege,  the container still fails to do "crictl images"  or "/usr/bin/crictl --runtime-endpoint=unix:///var/run/crio/crio.sock  --image-endpoint=unix:///var/run/crio/crio.sock image".

Any idea if there is a way to resolve this?
