### ISSUE TITLE
Feature/Question possible to use kustomize with image transformer on ImageCache?

### ISSUE THREAD

**Issue by mgeri** [senthilrch/kube-fledged#191]
We use kustomize for cluster deployment, and we are trying to use the image transformation with ImageCache without success.
We tried to add this configuration for image transformation:

```
images:
- path: spec/cacheSpec/images
  kind: ImageCache
```
But it fails, because it seems that the image transformer works with ScalarNode and not SequenceNode.
We don't know if we are missing something with kustomize or if something similar is needed to make the kustomize image transformer work:

```yaml
apiVersion: kubefledged.io/v1alpha2
kind: ImageCache
spec:
  cacheSpec:
  - images:
    - name: us.gcr.io/k8s-artifacts-prod/cassandra:v7
    - name: us.gcr.io/k8s-artifacts-prod/etcd:3.5.4-0
    nodeSelector:
      tier: backend
```

**Comment by mgeri** [comment]
It works using the following image transformation configuration, i.e., when `name` is a ScalarNode:
```yaml
images:
- path: spec/cacheSpec/images/name
  kind: ImageCache
```
If the `path` in the kustomize configuration point to a SequenceNode, it doesn't work.
I'm unsure if there is another way to set up a kustomize configuration that works with sequences. I tried to find docs and samples without success.
