### ISSUE TITLE
Enhancement: modify helm operator crd group to "charts.helm.kubefledged.io" & update openapiv3schema

### ISSUE THREAD

**Issue by senthilrch** [senthilrch/kube-fledged#88]
The CRD of the helm operator uses the group "charts.helm.k8s.io". Since *.k8s.io is a reserved group, propose to modify this to "charts.helm.kubefledged.io". Also update  openapiv3schema of the CRD.

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubefledgeds.charts.helm.kubefledged.io
spec:
  group: charts.helm.kubefledged.io
  names:
    kind: KubeFledged
    listKind: KubeFledgedList
    plural: kubefledgeds
    singular: kubefledged
  scope: Namespaced
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: KubeFledged is the Schema for the kubefledgeds API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of KubeFledged
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state of KubeFledged
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
```
