### ISSUE TITLE
Can't cache images from private ACR

### ISSUE THREAD

**Issue by francoran** [senthilrch/kube-fledged#96]
Hey,

I'm trying to cache few images from private Azure Container Registry,
ACR is linked to the cluster without secret, by role, pods are able to pull the relevant images.

here's my yaml
```
---
apiVersion: kubefledged.io/v1alpha2
kind: ImageCache
metadata:
  name: ml-imagecache
  namespace: services
  labels:
    app: kubefledged
    component: imagecache
spec:
  cacheSpec:
  - images:
    - devdynamicsacr.azurecr.io/private-a
    - devdynamicsacr.azurecr.io/private-b
    nodeSelector:
      namespace: "services"

```

logs - 

> },
    "status": {
        "completionTime": "2021-08-09T21:26:09Z",
        "failures": {
            "myreg.azurecr.io/private-a": [
                {
                    "message": "",
                    "node": "aks-m-20868404-vmss00006h",
                    "reason": ""
                },
                {
                    "message": "",
                    "node": "aks-m-20868404-vmss00006j",
                    "reason": ""
                },
                {
                    "message": "",
                    "node": "aks-m-20868404-vmss000004",
                    "reason": ""
                },
                {
                    "message": "",
                    "node": "aks-m-20868404-vmss000065",
                    "reason": ""
                },........

Global images like bitnami/redis are working as expected.
Any idea where can I get more details on the failure? "reason" is missing from logs
